import type { MenuCategory } from '@/types/menu';

export const defaultMenuStructure: MenuCategory[] = [
  {
    id: 'crew-management',
    label: '선원 관리',
    icon: 'Users',
    order: 1,
    is_active: true,
    items: [
      {
        id: 'crew-list',
        label: '선원 목록',
        path: '/crew',
        icon: 'Users',
        roles: ['ship_manager', 'manning_agency', 'crew'],
        order: 1,
        is_active: true,
      },
      {
        id: 'certificate-expiry',
        label: '증서 만료 현황',
        path: '/certificate-expiry',
        icon: 'AlertTriangle',
        roles: ['ship_manager', 'manning_agency'],
        order: 3,
        is_active: true,
      },
      {
        id: 'crew-evaluations',
        label: '고과 관리',
        path: '/crew-evaluations',
        icon: 'Star',
        roles: ['ship_manager'],
        order: 5,
        is_active: true,
      },
      {
        id: 'crew-medical',
        label: '상병 관리',
        path: '/crew-medical',
        icon: 'Stethoscope',
        roles: ['ship_manager'],
        order: 6,
        is_active: true,
      },
      {
        id: 'crew-management-settings',
        label: '선원 관리 설정',
        path: '/crew-management-settings',
        icon: 'Settings',
        roles: ['ship_manager'],
        order: 8,
        is_active: true,
      },
    ],
  },
  {
    id: 'ship-management',
    label: '선박 관리',
    icon: 'Ship',
    order: 2,
    is_active: true,
    items: [
      {
        id: 'ships',
        label: '선박 목록',
        path: '/ships',
        icon: 'Ship',
        roles: ['ship_owner', 'ship_manager'],
        order: 1,
        is_active: true,
      },
      {
        id: 'ship-management-settings',
        label: '선박 관리 설정',
        path: '/ship-management-settings',
        icon: 'Settings',
        roles: ['ship_manager'],
        order: 2,
        is_active: true,
      },
    ],
  },
  {
    id: 'recruitment',
    label: '구인구직',
    icon: 'Briefcase',
    order: 3,
    is_active: true,
    items: [
      {
        id: 'job-postings',
        label: '구인 공고',
        path: '/job-postings',
        icon: 'Briefcase',
        roles: ['ship_owner', 'ship_manager', 'manning_agency', 'crew'],
        order: 1,
        is_active: true,
      },
      {
        id: 'my-recommendations',
        label: '내 추천 선원',
        path: '/my-recommendations',
        icon: 'ListChecks',
        roles: ['manning_agency'],
        strictRoles: true,
        order: 2,
        is_active: true,
      },
    ],
  },
  {
    id: 'dispatch',
    label: '선원 발령',
    icon: 'Send',
    order: 4,
    is_active: true,
    items: [
      {
        id: 'recommendation-review',
        label: '추천 검토',
        path: '/recommendation-review',
        icon: 'FileCheck',
        roles: ['ship_manager'],
        order: 1,
        is_active: true,
      },
      {
        id: 'crew-rotation',
        label: '선원 교대 발령(배승)',
        path: '/crew-rotation',
        icon: 'RefreshCw',
        roles: ['ship_owner', 'ship_manager'],
        order: 2,
        is_active: true,
      },
      {
        id: 'dispatch-approval-inbox',
        label: '발령 결재함',
        path: '/dispatch-approval-inbox',
        icon: 'Inbox',
        roles: ['ship_manager'],
        order: 3,
        is_active: true,
      },
      {
        id: 'contract-management',
        label: '계약 관리',
        path: '/contract-management',
        icon: 'FileSignature',
        roles: ['ship_manager'],
        order: 4,
        is_active: true,
      },
      {
        id: 'crew-dispatch',
        label: '승진/강등 발령',
        path: '/crew-dispatch',
        icon: 'ArrowUpCircle',
        roles: ['ship_manager'],
        order: 5,
        is_active: true,
      },
    ],
  },
  {
    id: 'groupware',
    label: '그룹웨어',
    icon: 'Building2',
    order: 5,
    is_active: true,
    items: [
      {
        id: 'approval-inbox',
        label: '결재함',
        path: '/approval-inbox',
        icon: 'Inbox',
        roles: ['ship_manager', 'manning_agency'],
        order: 1,
        is_active: true,
      },
      {
        id: 'document-draft',
        label: '기안함',
        path: '/documents/new',
        icon: 'FileText',
        roles: ['ship_manager', 'admin', 'system_admin'],
        order: 2,
        is_active: true,
      },
      {
        id: 'shore-leave-request',
        label: '연차 신청',
        path: '/shore-leave-request',
        icon: 'CalendarDays',
        roles: ['ship_manager', 'admin', 'system_admin'],
        order: 3,
        is_active: true,
      },
      {
        id: 'sick-leave-request',
        label: '질병휴가 신청',
        path: '/sick-leave-request',
        icon: 'Stethoscope',
        roles: ['ship_manager', 'admin', 'system_admin'],
        order: 4,
        is_active: true,
      },
      {
        id: 'shore-leave-calendar',
        label: '직원 휴가 현황',
        path: '/shore-leave-calendar',
        icon: 'CalendarDays',
        roles: ['ship_manager', 'admin', 'system_admin'],
        order: 5,
        is_active: true,
      },
      {
        id: 'shore-leave-management',
        label: '육상 직원 휴가 관리',
        path: '/shore-leave-management',
        icon: 'CalendarDays',
        roles: ['ship_manager'],
        order: 6,
        is_active: true,
      },
      {
        id: 'employee-salary',
        label: '직원 급여관리',
        path: '/employee-salary',
        icon: 'Wallet',
        roles: ['ship_manager'],
        order: 7,
        is_active: true,
      },
      {
        id: 'my-payslips',
        label: '내 급여명세서',
        path: '/my-payslips',
        icon: 'Wallet',
        roles: ['ship_manager', 'admin', 'system_admin'],
        order: 8,
        is_active: true,
      },
      {
        id: 'groupware-settings',
        label: '설정',
        path: '/groupware-settings',
        icon: 'Settings',
        roles: ['ship_manager'],
        order: 9,
        is_active: true,
      },
      {
        id: 'homepage-posts',
        label: '게시판 관리',
        path: '/homepage-posts',
        icon: 'Newspaper',
        roles: ['ship_manager', 'admin', 'system_admin'],
        order: 9,
        is_active: true,
      },
    ],
  },
  {
    id: 'salary',
    label: '급여 관리',
    icon: 'DollarSign',
    order: 6,
    is_active: true,
    items: [
      {
        id: 'salary-templates',
        label: '급여 템플릿',
        path: '/salary/templates',
        icon: 'FileText',
        roles: ['ship_manager'],
        order: 1,
        is_active: true,
      },
      {
        id: 'salary-components',
        label: '급여 구성항목',
        path: '/salary-components',
        icon: 'Coins',
        roles: ['ship_manager'],
        order: 2,
        is_active: true,
      },
      {
        id: 'allotment-management',
        label: '송금 관리',
        path: '/allotment-management',
        icon: 'Banknote',
        roles: ['ship_manager'],
        order: 3,
        is_active: true,
      },
      {
        id: 'allowance-types',
        label: '수당/공제 기준 관리',
        path: '/allowance-types',
        icon: 'Coins',
        roles: ['ship_manager'],
        order: 4,
        is_active: true,
      },
      {
        id: 'crew-payroll',
        label: '선원 급여명세',
        path: '/crew-payroll',
        icon: 'Wallet',
        roles: ['ship_manager'],
        order: 5,
        is_active: true,
      },
      {
        id: 'crew-deferred-pay',
        label: '선원 후불성 급여 현황',
        path: '/crew-deferred-pay',
        icon: 'PiggyBank',
        roles: ['ship_manager'],
        order: 6,
        is_active: true,
      },
      {
        id: 'crew-sick-pay',
        label: '상병 수당 관리',
        path: '/crew-sick-pay',
        icon: 'Stethoscope',
        roles: ['ship_manager'],
        order: 7,
        is_active: true,
      },
    ],
  },
  {
    id: 'reports',
    label: '보고서/통계',
    icon: 'BarChart3',
    order: 7,
    is_active: true,
    items: [
      {
        id: 'reports-dashboard',
        label: '통계 대시보드',
        path: '/reports',
        icon: 'BarChart3',
        roles: ['ship_manager'],
        order: 1,
        is_active: true,
      },
    ],
  },
  {
    id: 'settings',
    label: '설정',
    icon: 'Settings',
    order: 8,
    is_active: true,
    items: [
      {
        id: 'company-info',
        label: '회사 정보 관리',
        path: '/company-info',
        icon: 'Building',
        roles: ['ship_manager'],
        order: 1,
        is_active: true,
      },
      {
        id: 'companies-owner',
        label: '선주사 관리',
        path: '/companies?type=owner',
        icon: 'Building2',
        roles: ['ship_manager'],
        order: 2,
        is_active: true,
      },
      {
        id: 'companies-manning',
        label: '선원 매닝사 관리',
        path: '/companies?type=manning',
        icon: 'Users',
        roles: ['ship_manager'],
        order: 3,
        is_active: true,
      },
      {
        id: 'manager-assignments',
        label: '선주 사용자 관리',
        path: '/manager-assignments',
        icon: 'UserCheck',
        roles: ['ship_manager'],
        order: 4,
        is_active: true,
      },
      {
        id: 'supervisor-management',
        label: '우리회사 담당자 관리',
        path: '/supervisor-management',
        icon: 'UserCheck',
        roles: ['ship_manager'],
        order: 5,
        is_active: true,
      },
      {
        id: 'user-groups',
        label: '사용자 관리',
        path: '/user-groups',
        icon: 'UserCog',
        roles: ['ship_manager'],
        order: 6,
        is_active: true,
      },
      {
        id: 'file-storage-settings',
        label: '파일 저장소 설정',
        path: '/settings/file-storage',
        icon: 'HardDrive',
        roles: ['ship_manager', 'admin', 'system_admin'],
        order: 7,
        is_active: true,
      },
      {
        id: 'file-management',
        label: '파일 관리',
        path: '/settings/files',
        icon: 'FolderOpen',
        roles: ['admin', 'system_admin'],
        strictRoles: true,
        order: 8,
        is_active: true,
      },
    ],
  },
  {
    id: 'accounting',
    label: '경리',
    icon: 'Landmark',
    order: 9,
    is_active: true,
    items: [
      {
        id: 'accounting-settings',
        label: '설정',
        path: '/accounting/settings',
        icon: 'Settings',
        roles: ['ship_manager'],
        order: 1,
        is_active: true,
      },
      {
        id: 'accounting-cashbook',
        label: '금전출납',
        path: '/accounting/cashbook',
        icon: 'Receipt',
        roles: ['ship_manager'],
        order: 2,
        is_active: true,
      },
      {
        id: 'accounting-expense-reflection',
        label: '지출결의 반영',
        path: '/accounting/expense-reflection',
        icon: 'FileCheck',
        roles: ['ship_manager'],
        order: 3,
        is_active: true,
      },
      {
        id: 'accounting-daily-report',
        label: '자금일보',
        path: '/accounting/daily-report',
        icon: 'FileText',
        roles: ['ship_manager'],
        order: 4,
        is_active: true,
      },
    ],
  },
];