import type { MenuCategory } from '@/types/menu';

export const defaultMenuStructure: MenuCategory[] = [
  {
    id: 'crew-management',
    label: '선원 관리',
    icon: 'Users',
    order: 1,
    is_active: true,
    items: [
      {
        id: 'crew-list',
        label: '선원 목록',
        path: '/crew',
        icon: 'Users',
        roles: ['ship_manager', 'manning_agency', 'crew'],
        order: 1,
        is_active: true,
      },
      {
        id: 'crew-assignment',
        label: '발령 관리',
        path: '/assignments',
        icon: 'Calendar',
        roles: ['ship_owner', 'ship_manager', 'manning_agency'],
        order: 2,
        is_active: true,
      },
      {
        id: 'crew-rotation',
        label: '선원 교대 발령',
        path: '/crew-rotation',
        icon: 'RefreshCw',
        roles: ['ship_owner', 'ship_manager'],
        order: 3,
        is_active: true,
      },
      {
        id: 'nationalities',
        label: '선원 국적 관리',
        path: '/nationalities',
        icon: 'Globe',
        roles: ['ship_manager'],
        order: 4,
        is_active: true,
      },
      {
        id: 'certificate-types',
        label: '증서 유형 관리',
        path: '/certificate-types',
        icon: 'FileText',
        roles: ['ship_manager'],
        order: 5,
        is_active: true,
      },
      {
        id: 'ranks',
        label: '직급 관리',
        path: '/ranks',
        icon: 'Award',
        roles: ['ship_manager'],
        order: 6,
        is_active: true,
      },
      {
        id: 'certificate-expiry',
        label: '증서 만료 현황',
        path: '/certificate-expiry',
        icon: 'AlertTriangle',
        roles: ['ship_manager', 'manning_agency'],
        order: 7,
        is_active: true,
      },
      {
        id: 'leave-management',
        label: '휴가 관리',
        path: '/leave-management',
        icon: 'CalendarOff',
        roles: ['ship_manager', 'manning_agency'],
        order: 8,
        is_active: true,
      },
      {
        id: 'crew-evaluations',
        label: '선원 평가',
        path: '/crew-evaluations',
        icon: 'Star',
        roles: ['ship_manager'],
        order: 9,
        is_active: true,
      },
      {
        id: 'contract-management',
        label: '계약 관리',
        path: '/contract-management',
        icon: 'FileSignature',
        roles: ['ship_manager'],
        order: 10,
        is_active: true,
      },
      {
        id: 'ports',
        label: '교대지 관리',
        path: '/ports',
        icon: 'Anchor',
        roles: ['ship_manager'],
        order: 11,
        is_active: true,
      },
    ],
  },
  {
    id: 'ship-management',
    label: '선박 관리',
    icon: 'Ship',
    order: 2,
    is_active: true,
    items: [
      {
        id: 'ships',
        label: '선박 목록',
        path: '/ships',
        icon: 'Ship',
        roles: ['ship_owner', 'ship_manager'],
        order: 1,
        is_active: true,
      },
      {
        id: 'ship-types',
        label: '선종/분류 관리',
        path: '/ship-types',
        icon: 'Layers',
        roles: ['ship_manager'],
        order: 2,
        is_active: true,
      },
      {
        id: 'ship-flags',
        label: '선적국 관리',
        path: '/ship-flags',
        icon: 'Flag',
        roles: ['ship_manager'],
        order: 3,
        is_active: true,
      },
      {
        id: 'fleet-management',
        label: '플릿 관리',
        path: '/fleet-management',
        icon: 'Layers',
        roles: ['ship_owner', 'ship_manager'],
        order: 4,
        is_active: true,
      },
    ],
  },
  {
    id: 'recruitment',
    label: '구인구직',
    icon: 'Briefcase',
    order: 3,
    is_active: true,
    items: [
      {
        id: 'job-postings',
        label: '구인 공고',
        path: '/job-postings',
        icon: 'Briefcase',
        roles: ['ship_owner', 'ship_manager', 'manning_agency', 'crew'],
        order: 1,
        is_active: true,
      },
      {
        id: 'my-recommendations',
        label: '내 추천 선원',
        path: '/my-recommendations',
        icon: 'ListChecks',
        roles: ['manning_agency'],
        order: 2,
        is_active: true,
      },
      {
        id: 'recommendation-review',
        label: '추천 검토',
        path: '/recommendation-review',
        icon: 'FileCheck',
        roles: ['ship_manager'],
        order: 3,
        is_active: true,
      },
    ],
  },
  {
    id: 'approval',
    label: '결재',
    icon: 'Inbox',
    order: 4,
    is_active: true,
    items: [
      {
        id: 'approval-inbox',
        label: '내 결재함',
        path: '/approval-inbox',
        icon: 'Inbox',
        roles: ['ship_manager', 'manning_agency'],
        order: 1,
        is_active: true,
      },
      {
        id: 'approval-archive',
        label: '완료 문서함',
        path: '/approval-archive',
        icon: 'Archive',
        roles: ['ship_manager', 'manning_agency'],
        order: 2,
        is_active: true,
      },
      {
        id: 'approval-management',
        label: '결재 캐비넷',
        path: '/approval-management',
        icon: 'FolderOpen',
        roles: ['ship_manager', 'manning_agency'],
        order: 3,
        is_active: true,
      },
      {
        id: 'approval-lines',
        label: '결재선 관리',
        path: '/approval-lines',
        icon: 'CheckSquare',
        roles: ['ship_manager'],
        order: 4,
        is_active: true,
      },
    ],
  },
  {
    id: 'salary',
    label: '급여 관리',
    icon: 'DollarSign',
    order: 5,
    is_active: true,
    items: [
      {
        id: 'salary-templates',
        label: '급여 템플릿',
        path: '/salary/templates',
        icon: 'FileText',
        roles: ['ship_manager'],
        order: 1,
        is_active: true,
      },
      {
        id: 'salary-components',
        label: '급여 구성항목',
        path: '/salary-components',
        icon: 'Coins',
        roles: ['ship_manager'],
        order: 2,
        is_active: true,
      },
      {
        id: 'allotment-management',
        label: '송금 관리',
        path: '/allotment-management',
        icon: 'Banknote',
        roles: ['ship_manager'],
        order: 3,
        is_active: true,
      },
    ],
  },
  {
    id: 'reports',
    label: '보고서/통계',
    icon: 'BarChart3',
    order: 6,
    is_active: true,
    items: [
      {
        id: 'reports-dashboard',
        label: '통계 대시보드',
        path: '/reports',
        icon: 'BarChart3',
        roles: ['ship_manager'],
        order: 1,
        is_active: true,
      },
    ],
  },
  {
    id: 'settings',
    label: '설정',
    icon: 'Settings',
    order: 6,
    is_active: true,
    items: [
      {
        id: 'companies-owner',
        label: '선주사 관리',
        path: '/companies?type=owner',
        icon: 'Building2',
        roles: ['ship_manager'],
        order: 1,
        is_active: true,
      },
      {
        id: 'companies-manning',
        label: '선원 매닝사 관리',
        path: '/companies?type=manning',
        icon: 'Users',
        roles: ['ship_manager'],
        order: 2,
        is_active: true,
      },
      {
        id: 'user-groups',
        label: '사용자 그룹 관리',
        path: '/user-groups',
        icon: 'UserCog',
        roles: ['ship_manager'],
        order: 3,
        is_active: true,
      },
      {
        id: 'manager-assignments',
        label: '선주 사용자 관리',
        path: '/manager-assignments',
        icon: 'UserCheck',
        roles: ['ship_manager'],
        order: 4,
        is_active: true,
      },
      {
        id: 'supervisor-management',
        label: '우리회사 담당자 관리',
        path: '/supervisor-management',
        icon: 'UserCheck',
        roles: ['ship_manager'],
        order: 5,
        is_active: true,
      },
      {
        id: 'shore-positions',
        label: '육상 직원 직급',
        path: '/shore-positions',
        icon: 'Briefcase',
        roles: ['ship_manager'],
        order: 6,
        is_active: true,
      },
      {
        id: 'org-chart',
        label: '조직도 관리',
        path: '/org-chart',
        icon: 'Network',
        roles: ['ship_manager'],
        order: 7,
        is_active: true,
      },
      {
        id: 'permissions',
        label: '권한 관리',
        path: '/permissions',
        icon: 'Shield',
        roles: ['ship_manager'],
        order: 8,
        is_active: true,
      },
      {
        id: 'menu-configuration',
        label: 'UI 구성 관리',
        path: '/menu-configuration',
        icon: 'Layout',
        roles: ['ship_manager'],
        order: 9,
        is_active: true,
      },
    ],
  },
];