import { lazy } from 'react';

const DashboardPage = lazy(() => import('@/pages/DashboardPage'));
const CrewManagementPage = lazy(() => import('@/pages/CrewManagementPage'));
const CrewDetailPage = lazy(() => import('@/pages/CrewDetailPage'));
const CrewInputPage = lazy(() => import('@/pages/CrewInputPage'));
const CrewAssignmentPage = lazy(() => import('@/pages/CrewAssignmentPage'));
const CrewRotationPage = lazy(() => import('@/pages/CrewRotationPage').then(m => ({ default: m.CrewRotationPage })));
const RotationPlanFormPage = lazy(() => import('@/pages/RotationPlanFormPage'));
const CrewRotationDetailPage = lazy(() => import('@/pages/CrewRotationDetailPage'));
const CrewBoardingFitDetailPage = lazy(() => import('@/pages/CrewBoardingFitDetailPage'));
const DispatchOrderPage = lazy(() => import('@/pages/DispatchOrderPage'));
const DispatchOrderListPage = lazy(() => import('@/pages/DispatchOrderListPage'));
const ShipManagementPage = lazy(() => import('@/pages/ShipManagementPage'));
const ShipTypeManagementPage = lazy(() => import('@/pages/ShipTypeManagementPage'));
const ShipFlagManagementPage = lazy(() => import('@/pages/ShipFlagManagementPage'));
const FleetManagementPage = lazy(() => import('@/pages/FleetManagementPage'));
const JobPostingsPage = lazy(() => import('@/pages/JobPostingsPage'));
const JobPostingFormPage = lazy(() => import('@/pages/JobPostingFormPage'));
const JobPostingRecommendationsPage = lazy(() => import('@/pages/JobPostingRecommendationsPage'));
const CrewRecommendationPage = lazy(() => import('@/pages/CrewRecommendationPage'));
const CrewRecommendationsPage = lazy(() => import('@/pages/CrewRecommendationsPage'));
const MyRecommendationsPage = lazy(() => import('@/pages/MyRecommendationsPage'));
const RecommendationReviewPage = lazy(() => import('@/pages/RecommendationReviewPage'));
const ApprovalLineManagementPage = lazy(() => import('@/pages/ApprovalLineManagementPage'));
const ApprovalInboxPage = lazy(() => import('@/pages/ApprovalInboxPage'));
const DispatchApprovalInboxPage = lazy(() => import('@/pages/DispatchApprovalInboxPage'));
const GroupwareSettingsPage = lazy(() => import('@/pages/GroupwareSettingsPage'));
const ApprovalDocumentDetailPage = lazy(() => import('@/pages/ApprovalDocumentDetailPage'));
const SupervisorManagementPage = lazy(() => import('@/pages/SupervisorManagementPage'));
const RanksPage = lazy(() => import('@/pages/RanksPage'));
const PermissionsPage = lazy(() => import('@/pages/PermissionsPage'));
const SalaryComponentsPage = lazy(() => import('@/pages/SalaryComponentsPage'));
const SalaryTemplatesPage = lazy(() => import('@/pages/SalaryTemplatesPage'));
const SalaryTemplateFormPage = lazy(() => import('@/pages/SalaryTemplateFormPage'));
const SalaryTemplateDetailPage = lazy(() => import('@/pages/SalaryTemplateDetailPage'));
const ShorePositionsPage = lazy(() => import('@/pages/ShorePositionsPage'));
const AllowanceTypesManagementPage = lazy(() => import('@/pages/AllowanceTypesManagementPage'));
const CrewPayrollManagementPage = lazy(() => import('@/pages/CrewPayrollManagementPage'));
const CrewPayrollDashboardPage = lazy(() => import('@/pages/CrewPayrollDashboardPage'));
const CrewDeferredPayReportPage = lazy(() => import('@/pages/CrewDeferredPayReportPage'));
const CrewSickPayManagementPage = lazy(() => import('@/pages/CrewSickPayManagementPage'));
const OrgChartManagementPage = lazy(() => import('@/pages/OrgChartManagementPage'));
const DocumentTypesManagementPage = lazy(() => import('@/pages/DocumentTypesManagementPage'));
const DocumentDraftPage = lazy(() => import('@/pages/DocumentDraftPage'));
const PortManagementPage = lazy(() => import('@/pages/PortManagementPage'));
const ProfilePage = lazy(() => import('@/pages/ProfilePage'));
const CompanyManagementPage = lazy(() => import('@/pages/CompanyManagementPage'));
const CompanyInfoPage = lazy(() => import('@/pages/CompanyInfoPage'));
const UserGroupManagementPage = lazy(() => import('@/pages/UserGroupManagementPage'));
const EmployeeCardManagementPage = lazy(() => import('@/pages/EmployeeCardManagementPage'));
const ManagerAssignmentPage = lazy(() => import('@/pages/ManagerAssignmentPage'));
const NationalityManagementPage = lazy(() => import('@/pages/NationalityManagementPage'));
const CertificateTypeManagementPage = lazy(() => import('@/pages/CertificateTypeManagementPage'));
const MenuConfigurationPage = lazy(() => import('@/pages/MenuConfigurationPage'));
const CertificateExpiryDashboardPage = lazy(() => import('@/pages/CertificateExpiryDashboardPage'));
const ReportsPage = lazy(() => import('@/pages/ReportsPage'));
const CrewEvaluationPage = lazy(() => import('@/pages/CrewEvaluationPage'));
const CrewMedicalPage = lazy(() => import('@/pages/CrewMedicalPage'));
const AllotmentManagementPage = lazy(() => import('@/pages/AllotmentManagementPage'));
const EmployeeSalaryManagementPage = lazy(() => import('@/pages/EmployeeSalaryManagementPage'));
const EmployeeMyPayslipsPage = lazy(() => import('@/pages/EmployeeMyPayslipsPage'));
const ContractManagementPage = lazy(() => import('@/pages/ContractManagementPage'));
const SignOffReasonsPage = lazy(() => import('@/pages/SignOffReasonsPage'));
const CrewManagementSettingsPage = lazy(() => import('@/pages/CrewManagementSettingsPage'));
const ShipManagementSettingsPage = lazy(() => import('@/pages/ShipManagementSettingsPage'));
const ShoreLeaveRequestPage = lazy(() => import('@/pages/ShoreLeaveRequestPage'));
const ShoreLeaveManagementPage = lazy(() => import('@/pages/ShoreLeaveManagementPage'));
const ShoreLeaveDetailPage = lazy(() => import('@/pages/ShoreLeaveDetailPage'));
const SickLeaveRequestPage = lazy(() => import('@/pages/SickLeaveRequestPage'));
const EmployeeLeaveCalendarPage = lazy(() => import('@/pages/EmployeeLeaveCalendarPage'));
const HomepagePostsPage = lazy(() => import('@/pages/HomepagePostsPage'));
const BankAccountManagementPage = lazy(() => import('@/pages/BankAccountManagementPage'));
const CardManagementPage = lazy(() => import('@/pages/CardManagementPage'));
const CashRegisterManagementPage = lazy(() => import('@/pages/CashRegisterManagementPage'));
const CashbookManagementPage = lazy(() => import('@/pages/CashbookManagementPage'));

export interface RouteEntry {
  path: string;
  component: React.LazyExoticComponent<React.ComponentType<unknown>>;
  exact?: boolean;
}

export const routeConfig: RouteEntry[] = [
  { path: '/dashboard', component: DashboardPage },
  { path: '/crew/management', component: CrewManagementPage },
  { path: '/crew/input/:recommendationId', component: CrewInputPage },
  { path: '/crew/input', component: CrewInputPage },
  { path: '/crew/new', component: CrewDetailPage },
  { path: '/crew/:id', component: CrewDetailPage },
  { path: '/crew', component: CrewManagementPage },
  { path: '/assignments', component: CrewAssignmentPage },
  { path: '/crew-rotation/new', component: RotationPlanFormPage },
  { path: '/crew-rotation/:id/edit', component: RotationPlanFormPage },
  { path: '/crew-rotation/:id', component: CrewRotationDetailPage },
  { path: '/crew-boarding-fit/:crewId', component: CrewBoardingFitDetailPage },
  { path: '/crew-rotation', component: CrewRotationPage },
  { path: '/crew-dispatch/new', component: DispatchOrderPage },
  { path: '/crew-dispatch', component: DispatchOrderListPage },
  { path: '/ships', component: ShipManagementPage },
  { path: '/ship-types', component: ShipTypeManagementPage },
  { path: '/ship-flags', component: ShipFlagManagementPage },
  { path: '/fleet-management', component: FleetManagementPage },
  { path: '/job-postings/new', component: JobPostingFormPage },
  { path: '/job-postings/:id/edit', component: JobPostingFormPage },
  { path: '/job-postings/:groupId/recommend/:rankId', component: CrewRecommendationPage },
  { path: '/job-postings/:groupId/recommendations', component: JobPostingRecommendationsPage },
  { path: '/job-postings', component: JobPostingsPage },
  { path: '/crew-recommendations', component: CrewRecommendationsPage },
  { path: '/my-recommendations', component: MyRecommendationsPage },
  { path: '/recommendation-review', component: RecommendationReviewPage },
  { path: '/dispatch-approval-inbox', component: DispatchApprovalInboxPage },
  { path: '/groupware-settings', component: GroupwareSettingsPage },
  { path: '/approval-lines', component: ApprovalLineManagementPage },
  { path: '/approval-inbox', component: ApprovalInboxPage },
  // 결재함/기안함/참조함/완료문서함/결재캐비닛을 결재함(ApprovalInboxPage) 하나로 통합 —
  // 기존 북마크·열린 탭이 깨지지 않도록 옛 경로도 같은 컴포넌트로 연결해둔다.
  { path: '/approval-archive', component: ApprovalInboxPage },
  { path: '/approval-management', component: ApprovalInboxPage },
  { path: '/supervisor-management', component: SupervisorManagementPage },
  { path: '/ranks', component: RanksPage },
  { path: '/permissions', component: PermissionsPage },
  { path: '/salary-components', component: SalaryComponentsPage },
  { path: '/salary/templates/new', component: SalaryTemplateFormPage },
  { path: '/salary/templates/:id/edit', component: SalaryTemplateFormPage },
  { path: '/salary/templates/:id', component: SalaryTemplateDetailPage },
  { path: '/salary/templates', component: SalaryTemplatesPage },
  { path: '/shore-positions', component: ShorePositionsPage },
  { path: '/org-chart', component: OrgChartManagementPage },
  { path: '/document-types', component: DocumentTypesManagementPage },
  { path: '/documents/new', component: DocumentDraftPage },
  { path: '/documents/:id', component: ApprovalDocumentDetailPage },
  { path: '/documents', component: ApprovalInboxPage },
  { path: '/my-documents', component: DocumentDraftPage },
  { path: '/ports', component: PortManagementPage },
  { path: '/profile', component: ProfilePage },
  { path: '/companies', component: CompanyManagementPage },
  { path: '/company-info', component: CompanyInfoPage },
  { path: '/user-groups', component: UserGroupManagementPage },
  { path: '/employee-cards', component: EmployeeCardManagementPage },
  { path: '/manager-assignments', component: ManagerAssignmentPage },
  { path: '/nationalities', component: NationalityManagementPage },
  { path: '/certificate-types', component: CertificateTypeManagementPage },
  { path: '/menu-configuration', component: MenuConfigurationPage },
  { path: '/certificate-expiry', component: CertificateExpiryDashboardPage },
  { path: '/reports', component: ReportsPage },
  { path: '/crew-evaluations', component: CrewEvaluationPage },
  { path: '/crew-medical', component: CrewMedicalPage },
  { path: '/allotment-management', component: AllotmentManagementPage },
  { path: '/employee-salary', component: EmployeeSalaryManagementPage },
  { path: '/my-payslips', component: EmployeeMyPayslipsPage },
  { path: '/contract-management', component: ContractManagementPage },
  { path: '/allowance-types', component: AllowanceTypesManagementPage },
  { path: '/crew-payroll/ship', component: CrewPayrollManagementPage },
  { path: '/crew-payroll', component: CrewPayrollDashboardPage },
  { path: '/crew-deferred-pay', component: CrewDeferredPayReportPage },
  { path: '/crew-sick-pay', component: CrewSickPayManagementPage },
  { path: '/sign-off-reasons', component: SignOffReasonsPage },
  { path: '/crew-management-settings', component: CrewManagementSettingsPage },
  { path: '/ship-management-settings', component: ShipManagementSettingsPage },
  { path: '/shore-leave-request', component: ShoreLeaveRequestPage },
  { path: '/shore-leave-management/:userId', component: ShoreLeaveDetailPage },
  { path: '/shore-leave-management', component: ShoreLeaveManagementPage },
  { path: '/sick-leave-request', component: SickLeaveRequestPage },
  { path: '/shore-leave-calendar', component: EmployeeLeaveCalendarPage },
  { path: '/referenced-documents', component: ApprovalInboxPage },
  { path: '/homepage-posts', component: HomepagePostsPage },
  { path: '/accounting/bank-accounts', component: BankAccountManagementPage },
  { path: '/accounting/cards', component: CardManagementPage },
  { path: '/accounting/cash-registers', component: CashRegisterManagementPage },
  { path: '/accounting/cashbook', component: CashbookManagementPage },
];
